schema = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3
# https://www.nerdfonts.com/cheat-sheet


[palette]
os = "#ACB0BE"
closer = "p:os"
rose = "#f5e0dc"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
marron = "#eba0ac"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"

[transient_prompt]
background = "transparent"
foreground = "p:text"
template = "\n> "

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

# [[blocks.segments]]
# foreground = "p:os"
# style = "plain"
# template = "{{.Icon}} "
# type = "os"

[[blocks.segments]]
foreground = "p:lavender"
style = "plain"
template = "\ue72f dhp >_"
type = "session"

[[blocks.segments]]
foreground = "p:pink"
style = "plain"
template = "{{ .Path }} "
type = "path"

[blocks.segments.properties]
folder_icon = "\ue5fe .."
home_icon = "~"
style = "agnoster_short"

[blocks.segments.properties.mapped_locations]
# "~" = "󰉍 "
"~/dotfiles" = " \uf013 "
"~/Downloads" = "󰉍 "


[[blocks.segments]]
style = "diamond"
leading_diamond = " "
trailing_diamond = ""
foreground = "transparent"
background = "p:lavender"
background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}p:blue{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:yellow{{ end }}",
    "{{ if gt .Ahead 0 }}p:mauve{{ end }}",
    "{{ if gt .Behind 0 }}p:mauve{{ end }}",
]
template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"
type = "git"

[blocks.segments.properties]
branch_icon = "\ue725 "
cherry_pick_icon = "\ue29b "
commit_icon = "\uf417 "
fetch_status = true
fetch_upstream_icon = true
merge_icon = "\ue727 "
no_commits_icon = "\uf0c3 "
rebase_icon = "\ue728 "
revert_icon = "\uf0e2 "
tag_icon = "\uf412 "

[[blocks]]
alignment = "right"
type = "prompt"

[[blocks.segments]]
foreground = "#007ACC"
template = " {{ .CurrentDate | date .Format }} "
style = "plain"
type = "time"

[blocks.segments.properties]
time_format = "15:04:05"

[[blocks.segments]]
type = "executiontime"
style = "diamond"
leading_diamond = " "
trailing_diamond = " "
foreground = "transparent"
background = "p:mauve"
template = "  {{ .FormattedMs }} "

[blocks.segments.properties]
threshold = 500
style = "austin"
always_enabled = true

[[blocks.segments]]
type = "python"
style = "diamond"
leading_diamond = " "
trailing_diamond = ""
foreground = "transparent"
background = "p:blue"
template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{.Major}}.{{.Minor }}{{ end }} "

[blocks.segments.properties]
always_enabled = true

[[blocks.segments]]
type = "ytm"
style = "plain"
api_url = "http://127.0.0.1:9863"
foreground = "#ffffff"
background = "#FF0000"

[blocks.segments.properties]
always_enabled = true
playing_icon = " "
paused_icon = " "
stopped_icon = " "

[[blocks.segments]]
type = "battery"
style = "diamond"
leading_diamond = " "
trailing_diamond = " "
foreground = "#193549"
background = "#ffeb3b"
background_templates = [
    "{{if eq \"Charging\" .State.String}}#40c4ff{{end}}",
    "{{if eq \"Discharging\" .State.String}}#ff5722{{end}}",
    "{{if eq \"Full\" .State.String}}#4caf50{{end}}",
]
template = " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }} "

[blocks.segments.properties]
discharging_icon = " "
charging_icon = " "
charged_icon = " "


# 프롬프트 라인
[[blocks]]
newline = true
alignment = "left"
type = "prompt"

[[blocks.segments]]
style = "plain"
foreground = "p:text"
template = "\uf105"
type = "text"
