schema = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[palette]
os = "#ACB0BE"
closer = "p:os"
pink = "#F5C2E7"
lavender = "#B4BEFE"
blue = "#89B4FA"

[transient_prompt]
background = "transparent"
foreground = "#ffffff"
template = "{{ .Shell }}> "

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

[[blocks.segments]]
foreground = "p:os"
style = "plain"
template = "{{.Icon}} "
type = "os"

[[blocks.segments]]
foreground = "p:blue"
style = "plain"
template = "dhp >_"
type = "session"

[[blocks.segments]]
foreground = "p:pink"
style = "plain"
template = "{{ .Path }} "
type = "path"
exclude_folders = [ "~/dotfiles/.*" ]

[blocks.segments.properties]
folder_icon = "\ue5fe .."
home_icon = "~"
style = "agnoster_short"

# https://www.nerdfonts.com/cheat-sheet
[[blocks.segments]]
foreground = "p:pink"
style = "plain"
template = "{{ .Path }}"
type = "path"
include_folders = [ "~/dotfiles/.*" ]

[blocks.segments.properties]
folder_icon = "\uf444 "
home_icon = "~"
style = "agnoster_short"

[[blocks.segments]]
style = "diamond"
leading_diamond = " "
trailing_diamond = ""
foreground = "#193549"
background = "#ffeb3b"
background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}",
  "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
  "{{ if gt .Behind 0 }}#B388FB{{ end }}"
]
template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"
type = "git"

[blocks.segments.properties]
branch_icon = "\ue725 "
cherry_pick_icon = "\ue29b "
commit_icon = "\uf417 "
fetch_status = true
fetch_upstream_icon = true
merge_icon = "\ue727 "
no_commits_icon = "\uf0c3 "
rebase_icon = "\ue728 "
revert_icon = "\uf0e2 "
tag_icon = "\uf412 "

[[blocks]]
alignment = "right"
filler = ". "
padding = 3
type = "prompt"


[[blocks.segments]]
type = "python"
style = "plain"
foreground = "transparent"
background = "p:lavender"
template = "  {{ .Full }} "

[[blocks.segments]]
type = "ytm"
style = "plain"
foreground = "#ffffff"
background = "#FF0000"

[blocks.segments.properties]
playing_icon = " "
paused_icon = " "
stopped_icon = " "

# 프롬프트 라인 
[[blocks]]
newline = true
alignment = "left"
type = "prompt"

[[blocks.segments]]
style = "plain"
foreground = "p:closer"
template = "\uf105"
type = "text"



