# >>> goto >>>
[[manager.prepend_keymap]]
on = ["g", "1"]
run = "cd C:"
desc = " C"

[[manager.prepend_keymap]]
on = ["g", "2"]
run = "cd D:"
desc = " D"

[[manager.prepend_keymap]]
on = ["g", "3"]
run = "cd E:"
desc = " E"

[[manager.prepend_keymap]]
on = ["g", "4"]
run = "cd F:"
desc = " F"

[[manager.prepend_keymap]]
on = ["g", "5"]
run = "cd G:"
desc = " G"

[[manager.prepend_keymap]]
on = ["g", "6"]
run = "cd H:"
desc = " H"

[[manager.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Downloads"
desc = "다운로드 폴더"

[[manager.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/dotfiles"
desc = "닷파일"

[[manager.prepend_keymap]]
on = ["g", "w"]
run = "cd ~/workspaces"
desc = "workspace"

[[manager.prepend_keymap]]
on = ["g", "o"]
run = "cd ~/Obsidian"
desc = "Obsidian"

[[manager.prepend_keymap]]
on = ["g", "f"]
run = 'search_do --via=fd --args="-d 3"'
desc = "flat 뷰"

# * edit profiles 
[[manager.prepend_keymap]]
on = ["e", "p"]
run = 'shell "cursor ~/.zshrc"'
desc = "프로필 편집"

[[manager.prepend_keymap]]
on = ["e", "t"]
run = 'shell "cursor ~/.config/oh-my-posh/dh_theme.toml"'
desc = "프롬프트 테마 편집"

[[manager.prepend_keymap]]
on = ["e", "a"]
run = 'shell "cursor ~/.zshrc"'
desc = "오토핫키 편집(윈도우) 수정필요"

# 템플릿 파일 만들기 
[[manager.prepend_keymap]]
run = 'shell "mkdir test"'
on = ["n", "h"]
desc = "한글 원피양식"

# ! >>> move >>> 
[[manager.prepend_keymap]]
on = "<F2>"
run = 'rename --cursor=before_ext'

[[manager.prepend_keymap]]
on = "<Home>"
run = 'arrow top'

[[manager.prepend_keymap]]
on = "<End>"
run = 'arrow bot'


# open workspaces
# open sites 
# python snippets : 파이썬 명령어 
# $n (Unix) / %n (Windows): The N-th selected file, starting from 1. e.g. $2 represents the second selected file.
# $@ (Unix) / %* (Windows): All selected files, i.e. $1, $2, ..., $n.
# $0 (Unix) / %0 (Windows): The hovered file.
