# https://yazi-rs.github.io/docs/configuration/yazi#preview
[manager]
show_hidden = false
sort_dir_first = true
sort_by = "natural"
linemode = "size"
show_symlink = true
mouse_events   = [ "click", "scroll", "drag" ]
title_format   = "{cwd}"
ratio = [1, 3, 5]

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_delay     = 30
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]


[tasks]
micro_workers    = 10
macro_workers    = 10
bizarre_retry    = 3
image_alloc      = 536870912  # 512MB
image_bound      = [ 5000, 5000 ]
suppress_preload = false

[opener]
play = [
	{ run = '"C:\Program Files\VideoLAN\VLC\vlc.exe" %*', orphan = true, for = "windows", desc = "VLC로 재생하기" },
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '"C:\Program Files\Notepad++\notepad++.exe" %*', block = true, for = "windows", desc = "notepad++로 편집하기" },
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]

edit_nvim = [
	{ run = "nvim %*", block = true, for = "windows", desc = "nvim 편집하기" },
	{ run = 'nvim "$@"', block = true, for = "unix" },
]

open = [
	{ run = 'start "" %*', desc = "기본 프로그램으로 열기", for = "windows" },
	{ run = 'open -a Finder "$@"', desc = "Finder", for = "macos" },
	{ run = 'xdg-open "$@"', desc = "xdg-open", for = "linux" },
]

reveal = [
	{ run = 'xdg-open "$(dirname "$1")"', desc = "경로열기", for = "linux" },
	{ run = 'OneCommander %*', orphan = true, desc = "경로열기", for = "windows" },
	{ run = 'open -R "$1"', desc = "경로열기", for = "macos" },
]

open_dir = [
	{ run = 'OneCommander %*', for = "windows", desc = "원커맨더 경로 열기" },
	{ run = 'open -R "$1"', desc = "Finder 보기", for = "macos" },
	{ run = 'xdg-open "$@"', for = "linux" },
]

extract = [
	{ run = 'ouch d -y "%*"', desc = "압축해제", for = "windows" },
	{ run = 'ouch d -y "$@"', desc = "압축해제", for = "unix" },
]

[open]
rules = [
	{ mime = "text/*", use = ["edit", "edit_nvim", "open", "open_dir"] },
	{ mime = "video/*", use = "play" },

	# Multiple openers for a single rule
	{ name = "*.html", use = ["open", "edit"] },

	# 한글 문서
	{ name = "*.hwp*", use = ["open", "open_dir"] },

	# zip
	{ name = "*.zip*", use = ["open", "open_dir", "extract"] },
	{ name = "*.tar*", use = ["open", "open_dir", "extract"] },
	{ name = "*.rar", use = ["open", "open_dir", "extract"] },
	{ name = "*.gz", use = ["open", "open_dir", "extract"] },
	{ name = "*.gx", use = ["open", "open_dir", "extract"] },
	# 모든 것 ?
	{ name = "*", use = ["open", "open_dir", "edit"] },
	# 경로
	{ name = "*/", use = ["open", "open_dir"] },
]

[plugin]
prepend_previewers = [
    # {name = "*/", run  = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'},
  	# structured text
	{ name = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
	{ name = "*.csv", run  = 'piper -- bat -p --color=always "$1"'}, # for csv files
	# { name = "*.csv", run  = 'piper -- rich --csv "$1"'}, # for csv files
	{ name = "*.txt", run  = 'piper -- bat -p --color=always "$1"'},
    { name = "*.rst", run = 'piper -- rich --rst --emoji --left -n --force-terminal --panel=square -g --max-width $w "$1"'},
    { name = "*.ipynb", run = 'piper -- rich --ipynb --force-terminal --panel=square -g --max-width $w "$1"'},
    # { name = "*.json", run = 'piper -- rich --json --force-terminal -W $w "$1"'},
    { name = "*.tsv", run = "duckdb"},
    { name = "*.parquet", run = "duckdb" },

    # docs
    {name = "*.hwpx", run = 'piper -- unzip -p "$1" "Preview/PrvText.txt" | rich -y -a square --title="$1" -'},

	# Archive
	{ name = "*.zip", run = "ouch" },
	{ name = "*.tar", run = "ouch" },
	{ name = "*.rar", run = "ouch" },
	{ mime = "application/x-bzip2", run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar", run = "ouch" },
	{ mime = "application/x-xz", run = "ouch" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

# [[plugin.append_previewers]]
# name = "*"
# run  = 'piper -- hexyl --border=none --terminal-width=$w "$1"'

[input]
cursor_blink = true

# cd
cd_title  = "경로 이동하기:"
cd_origin = "top-center"
cd_offset = [ 0, 2, 50, 3 ]

# create
create_title  = [ "파일 만들기:", "경로 만들기:" ]
create_origin = "top-center"
create_offset = [ 0, 2, 50, 3 ]

# rename
rename_title  = "이름 변경하기:"
rename_origin = "hovered"
rename_offset = [ 0, 1, 50, 3 ]

# filter
filter_title  = "필터:"
filter_origin = "top-center"
filter_offset = [ 0, 2, 50, 3 ]

# find
find_title  = [ "다음 찾기:", "이전 찾기:" ]
find_origin = "top-center"
find_offset = [ 0, 2, 50, 3 ]

# search
search_title  = "{n}으로 검색:"
search_origin = "top-center"
search_offset = [ 0, 2, 50, 3 ]

# shell
shell_title  = [ "쉘:", "쉘 (block):" ]
shell_origin = "top-center"
shell_offset = [ 0, 2, 50, 3 ]

[confirm]
# trash
trash_title 	= "{n}개의 파일 삭제하기"
trash_origin	= "center"
trash_offset	= [ 0, 0, 70, 20 ]

# delete
delete_title 	= "영구적으로 {n}개의 파일 삭제하기?"
delete_origin	= "center"
delete_offset	= [ 0, 0, 70, 20 ]

# overwrite
overwrite_title   = "파일 덮어쓰기"
overwrite_content = "다음의 파일을 덮어쓰게 됩니다:"
overwrite_origin  = "center"
overwrite_offset  = [ 0, 0, 50, 15 ]

# quit
quit_title   = "종료?"
quit_content = "다음의 작업도 종료됩니다."
quit_origin  = "center"
quit_offset  = [ 0, 0, 50, 15 ]

[pick]
open_title  = "다음으로 열기:"
open_origin = "hovered"
open_offset = [ 0, 1, 50, 7 ]

[which]
sort_by      	 = "none"
sort_sensitive = false
sort_reverse 	 = false
sort_translit  = false
