# https://yazi-rs.github.io/docs/configuration/yazi#preview
[manager]
show_hidden = false
sort_dir_first = true
sort_by = "natural"
linemode = "size"
show_symlink = true
moust_events = "click_and_scroll_move_drag"
ratio = [1, 2, 5]

[opener]
play = [
	{ run = '"C:\Program Files\VideoLAN\VLC\vlc.exe" %*', orphan = true, for = "windows", desc = "VLC로 재생하기" },
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '"C:\Program Files\Notepad++\notepad++.exe" %*', block = true, for = "windows", desc = "notepad++로 편집하기" },
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]

edit_nvim = [
	{ run = "nvim %*", block = true, for = "windows", desc = "nvim 편집하기" },
	{ run = 'nvim "$@"', block = true, for = "unix" },
]

open = [
	{ run = 'start "" %*', desc = "기본 프로그램으로 열기", for = "windows" },
	{ run = 'xdg-open "$@"', desc = "기본 프로그램으로 열기", for = "unix" },
]

open_dir = [
	{ run = 'OneCommander %*', for = "windows", desc = "원커맨더 경로 열기" },
	{ run = 'xdg-open "$@"', for = "unix" },
]

extract = [
	{ run = 'ouch d -y "%*"', desc = "압축해제", for = "windows" },
	{ run = 'ouch d -y "$@"', desc = "압축해제", for = "unix" },
]

[open]
rules = [
	{ mime = "text/*", use = ["edit", "edit_nvim", "open", "open_dir"] },
	{ mime = "video/*", use = "play" },

	# Multiple openers for a single rule
	{ name = "*.html", use = ["open", "edit"] },

	# 한글 문서 
	{ name = "*.hwp*", use = ["open", "open_dir"] },
	
	# zip 
	{ name = "*.zip*", use = ["open", "open_dir", "extract"] },
	
	# 모든 것 ?
	{ name = "*", use = ["open", "open_dir", "edit"] },
]

[plugin]
prepend_previewers = [
	{ name = "*.md", run = "glow" },
	# structured text 
	{ name = "*.csv", run = "rich-preview"}, # for csv files
    { name = "*.rst", run = "rich-preview"}, # for restructured text (.rst) files
    { name = "*.ipynb", run = "rich-preview"}, # for jupyter notebooks (.ipynb)
    { name = "*.json", run = "rich-preview"}, # for json (.json) files
	
	# { mime = "text/csv", run = "miller"},
	{ name = "*.ipynb", run = "nbpreview" },
	#	{ name = "*.csv", run = "duckdb" },  
	{ name = "*.tsv", run = "duckdb" },  
    { name = "*.json", run = "duckdb" },  
    { name = "*.parquet", run = "duckdb" },  
	
	# Archive 
	{ name = "*.zip",            run = "ouch" },
	{ name = "*.tar",           run = "ouch" },
	{ name = "*.rar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/x-xz",            run = "ouch" },
]

prepend_preloaders = [  
	{ name = "*.tsv", run = "duckdb", multi = false },  
    { name = "*.csv", run = "duckdb", multi = false },  
    { name = "*.json", run = "duckdb", multi = false },  
    { name = "*.parquet", run = "duckdb", multi = false },
    { name = "*.db", run = "duckdb" },
    { name = "*.duckdb", run = "duckdb" },
    ]
	
# append_previewers = [
  # { name = "*", run = "hexyl" },
# ]